services:
    - type: web
      name: fastapi-app
      env: python
      region: oregon
      plan: free
      buildCommand: pip install -r requirements.txt && python -m nltk.downloader punkt stopwords
      startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
      rootDir: fastapi-app
  
    - type: web
      name: streamlit-app
      env: python
      region: oregon
      plan: free
      buildCommand: pip install -r requirements.txt
      startCommand: streamlit run main.py --server.port 8501 --server.address 0.0.0.0
      rootDir: app